Config/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import*
from inicio.views import IndexView
from login.views import *
from dashboard.views import*
from django.contrib.auth import views as auth_views
from inicio.views import enviar_correo

urlpatterns = [
    path('', IndexView.as_view(), name='index_pr'),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('app/',include ('app.urls')),
    # path('password_reset/',auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html'), name='password_reset'), 
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'), name='password_reset_done'), 
    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'),name='password_reset_confirm'), 
    # path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'), name='password_reset_complete'),  
    path('enviar_correo/', enviar_correo, name='enviar_correo'),                                                                                                                     
]

app/urls.py
from django.urls import path
from app.views.backup.views import *
from app.views.Categoria.views import *
from app.views.Ubicacion.views import *
from app.views.Proveedor.views import * 
from app.views.Cliente.views import *
from app.views.Tipo.views import *
from app.views.Producto.views import *
from app.views.Normativa.views import *
from app.views.Ventas.views import *
from app.views.Compras.views import *
from app.views.Stock.views import *
from app.views.Usuario.views import *
from app.views.Dcompras.views import *
from app.views.Dventas.views import *
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'app'

urlpatterns = [

    #-------------------------------------------------- Categoría --------------------------------------------------
    
    path('categoria/listar/', CategoriaListView.as_view(), name='categoria_listar'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editarC'),
    path('categoria/eliminar/<int:id_categ>/', CategoriaListView.eliminar_categoria, name='categoria_eliminar'), 
    
    #-------------------------------------------------- Cliente ----------------------------------------------------
    
    path('cliente/listar/', ClienteListView.as_view(), name='cliente_listar'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editarCli'),
    path('cliente/eliminar/<int:id_cliente>/', ClienteListView.EliminarCliente, name='cliente_eliminar'),
    
    #-------------------------------------------------- Compras ----------------------------------------------------
    
    path('compras/listar/', ComprasListView.as_view(), name='compras_listar'),
    path('compras/crear/', ComprasCreateView.as_view(), name='compras_crear'),
    path('compras/editar/<int:pk>/', ComprasUpdateView.as_view(), name='compras_editar'),
    path('obtener-datos-proveedor/', obtener_datos_proveedor, name='obtener_datos_proveedor'),
    path('compras/<int:compra_id>/cambiar-estado/', cambiar_estado_compra, name='cambiar_estado_compra'),
    
    
        #-------------------------------------------------- Dcompras --------------------------------------------------------
    
    path('detalle-compras/listar/', DetalleCompraListView.as_view(), name='detallecompra_listar'),
    path('detalle-compras/crear/', DetalleCompraCreateView.as_view(), name='detallecompra_crear'),
    path('detalle-compras/editar/<int:pk>/', DetalleCompraUpdateView.as_view(), name='detallecompra_editar'),
    path('detalle-compras/eliminar/<int:id_compraD>/', DetalleCompraListView.EliminarComprasD,name='detallecompra_eliminar'),
    path('compras/detalles/<int:compra_id>/', DetalleCompraCreateView.as_view(), name='detalle_compra'),
    
    
    #-------------------------------------------------- Normativa --------------------------------------------------
    
    path('normativa/listar/', NormativaListView.as_view(), name='normativa_listar'),
    path('normativa/crear/', NormativaCreateView.as_view(), name='normativa_crear'),
    path('normativa/editar/<int:pk>/', NormativaUpdateView.as_view(), name='normativa_editarN'),
    path('normativa/eliminar/<int:id_norma>/', NormativaListView.EliminarNormativa, name='normativa_eliminar'),
    
    #-------------------------------------------------- Usuario ---------------------------------------------------
    
    path('usuario/listar/', UsuarioListView.as_view(), name='usuario_listar'),
    path('usuario/crear/', UsuarioCreateView.as_view(), name='usuario_crear'),
    path('usuario/editar/<int:pk>/', UsuarioUpdateView.as_view(), name='usuario_editar'),
    path('usuario/eliminar/<int:id_usuario>/', UsuarioListView.EliminarUsuario, name='usuario_eliminar'),
    path('acceso_denegado/', TemplateView.as_view(template_name='acceso_denegado.html'), name='acceso_denegado'),
    
    #-------------------------------------------------- Producto --------------------------------------------------

    path('producto/listar/', ProductoListView.as_view(), name='producto_listar'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editarP'),
    path('producto/eliminar/<int:id_producto>/', ProductoListView.EliminarProducto, name='producto_eliminar'),
    
    #-------------------------------------------------- Proveedor --------------------------------------------------
    
    path('proveedor/listar/', ProveedorListView.as_view(), name='proveedor_listar'),
    path('proveedor/crear/', ProveedorCreateView.as_view(), name='proveedor_crear'),
    path('proveedor/editar/<int:pk>/', ProveedorUpdateView.as_view(), name='proveedor_editar'),
    path('proveedor/eliminar/<int:id_prove>/', ProveedorListView.EliminarProveedor, name='proveedor_eliminar'),
    
    #-------------------------------------------------- Tipos de productos -----------------------------------------

    path('tipo/listar/', TipoListView.as_view(), name='tipo_listar'),
    path('tipo/crear/', TipoCreateView.as_view(), name='tipo_crear'),
    path('tipo/editar/<int:pk>/', TipoUpdateView.as_view(), name='tipo_editarTP'),
    path('tipo/eliminar/<int:id_tipo>/', TipoListView.EliminarTipo, name='tipo_eliminar'),

    #-------------------------------------------------- Ubicación --------------------------------------------------
    
    path('ubicacion/listar/', UbicacionListView.as_view(), name='ubicacion_listar'),
    path('ubicacion/crear/', UbicacionCreateView.as_view(), name='ubicacion_crear'),
    path('ubicacion/eliminar/<int:id_ubica>/', UbicacionListView.EliminarUbicacion, name='ubicacion_eliminar'),
    path('municipios-por-departamento/', municipios_por_departamento, name='municipios_por_departamento'),

    #-------------------------------------------------- Ventas ----------------------------------------------------
    path('ventas/listar/', VentasListView.as_view(), name='venta_listar'),
    path('ventas/crear/', VentasCreateView.as_view(), name='venta_crear'),
    path('ventas/editar/<int:pk>/', VentasUpdateView.as_view(), name='venta_editar'),
    path('cambiar-estado-venta/<int:venta_id>/',cambiar_estado_venta, name='cambiar_estado_venta'),

    #-------------------------------------------------- Dventas ---------------------------------------------------
    
    path('detalle-venta/', DetalleVentaListView.as_view(), name='detalleventa_listar'),
    path('detalle-venta/editar/<int:pk>/', DetalleVentaUpdateView.as_view(), name='detalleventa_editar'),
    path('ventas/detalle/<int:venta_id>/', VentaDetalleCreateView.as_view(), name='detalle_venta'),

    #-------------------------------------------------- Backup del sistema ----------------------------------------
    
    path('backup/', backup_view, name='backup'),
    path('backup/create/', backup_database, name='respaldo'),
    path('backup/restore/', restore_database, name='restauracion'),
    path('backup/delete/', delete_backup, name='eliminar_archivo'),

    #-------------------------------------------------- Stock -----------------------------------------------------
    
    path('stock/listar/', StockListView.as_view(), name='listar_stock'),
]

if settings.DEBUG:
    urlpatterns += static('/backups/', document_root=settings.BACKUP_ROOT)

app/views/Proveedor/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from app.models import Proveedor
from app.forms import ProveedorForm
from app.choices import Tipo_Documento_Choices, Tipo_Persona_Choices
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.http import require_POST
from app.mixins import LoginRequiredMixin

class ProveedorListView(LoginRequiredMixin,ListView):
    model = Proveedor
    template_name = 'Proveedor/listar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Listado de Proveedores'
        context['entidad'] = 'Proveedores'
        context['crear_url'] = reverse_lazy('app:proveedor_crear')
        context['tipo_documento'] = Tipo_Documento_Choices
        context['tipo_persona'] = Tipo_Persona_Choices
         # Agregar breadcrumbs
        context['breadcrumbs'] = [
            {'nombre': 'Modulos', 'url': '/dashboard'},
            {'nombre': 'Proveedor', 'url': reverse_lazy('app:proveedor_listar')},
        ]
        return context
    
    def get_queryset(self):
        queryset = super().get_queryset()

        # Obtener los parámetros GET
        tipo_persona = self.request.GET.get('tipo_persona')
        nombres = self.request.GET.get('nombres')
        tipo_documento = self.request.GET.get('tipo_documento')
        correo = self.request.GET.get('correo')
        telefono = self.request.GET.get('telefono')
        numero_documento = self.request.GET.get('numero_documento')

        # Aplicar filtros si los parámetros existen
        if tipo_persona:
            queryset = queryset.filter(tipo_persona=tipo_persona)
        if nombres:
            queryset = queryset.filter(nombres__icontains=nombres)
        if tipo_documento:
            queryset = queryset.filter(tipo_documento=tipo_documento)
        if correo:
            queryset = queryset.filter(correo__icontains=correo)
        if telefono:
            queryset = queryset.filter(telefono__icontains=telefono)
        if numero_documento:
            queryset = queryset.filter(numero_documento__icontains=numero_documento)

        return queryset

    @require_POST
    @user_passes_test(lambda u: u.is_superuser or u.is_staff)
    def EliminarProveedor(request, id_prove):
        try:
            prove = get_object_or_404(Proveedor, pk=id_prove)
            prove.delete()
            return JsonResponse({'status': 'success', 'message': 'Proveedor eliminado correctamente'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    
class ProveedorCreateView(LoginRequiredMixin,CreateView):
    model = Proveedor
    form_class = ProveedorForm
    template_name = 'Proveedor/crear.html'
    success_url = reverse_lazy('app:proveedor_listar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Crear Proveedor'
        context['entidad'] = 'Proveedor'
        context['listar_url'] = reverse_lazy('app:proveedor_listar')
     # Agregar breadcrumbs
        context['breadcrumbs'] = [
            {'nombre': 'Modulos', 'url': '/dashboard'},
            {'nombre': 'Proveerdor', 'url': reverse_lazy('app:proveedor_listar')},
            {'nombre': 'Crear Proveedor', 'url': reverse_lazy('app:proveedor_crear')},
        ]
        
        return context


    def form_valid(self, form):
        form.save()
        return JsonResponse({
            'success': True,
            'message': 'Proveedor creado exitosamente',
        })

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return super().form_invalid(form)

class ProveedorUpdateView(LoginRequiredMixin,UpdateView):
    model = Proveedor
    form_class = ProveedorForm
    template_name = 'Proveedor/editarProv.html'
    success_url = reverse_lazy('app:proveedor_listar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Actualizar Proveedor'
        context['entidad'] = 'Proveedor'
        context['listar_url'] = reverse_lazy('app:proveedor_listar')
         # Añadir breadcrumbs
        context['breadcrumbs'] = [
            {'nombre': 'Modulos', 'url': '/dashboard'},
            {'nombre': 'Proveedor', 'url': reverse_lazy('app:proveedor_listar')},
            {'nombre': 'Editar Proveedor', 'url': reverse_lazy('app:proveedor_editar', args=[self.object.pk])},
        ]

        return context

    def form_valid(self, form):
        form.save()
        return JsonResponse({
            'success': True,
            'message': 'Proveedor actualizado exitosamente',
        })

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return super().form_invalid(form)

app/templates/Proveedor/listar.html
{% extends "listar.html" %}
{# Extiende la plantilla base 'listar.html' #}

{% load static %}
{# Carga la etiqueta estática para usar archivos estáticos #}

{% block filtro_form_contenido %}
{# Bloque para el formulario de filtrado #}
<form method="GET" action="{% url 'app:proveedor_listar' %}">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="tipo_persona">Tipo de Persona</label>
                <select class="form-control" id="tipo_persona" name="tipo_persona">
                    <option value="">Todos</option>
                    {% for key, value in tipo_persona_choices %}
                        <option value="{{ key }}" {% if request.GET.tipo_persona == key %}selected{% endif %}>
                            {{ value }}
                        </option>
                    {% endfor %}
                </select>
                {# Desplegable para seleccionar el tipo de persona (e.g., Jurídica, Natural) #}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="nombres">Nombres / Razón Social</label>
                <input type="text" class="form-control" id="nombres" name="nombres" placeholder="Ingrese los nombres" value="{{ request.GET.nombres }}">
                {# Campo de texto para ingresar los nombres del proveedor #}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="tipo_documento">Tipo de Documento</label>
                <select class="form-control" id="tipo_documento" name="tipo_documento">
                    <option value="">Todos</option>
                    {% for key, value in tipo_documento_choices %}
                        <option value="{{ key }}" {% if request.GET.tipo_documento == key %}selected{% endif %}>
                            {{ value }}
                        </option>
                    {% endfor %}
                </select>
                {# Desplegable para seleccionar el tipo de documento (e.g., DNI, RUC) #}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="numero_documento">Número de Documento</label>
                <input type="text" class="form-control" id="numero_documento" name="numero_documento" placeholder="Ingrese el número de documento" value="{{ request.GET.numero_documento }}">
                {# Campo de texto para ingresar el número de documento del proveedor #}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="correo">Correo</label>
                <input type="email" class="form-control" id="correo" name="correo" placeholder="Ingrese el correo" value="{{ request.GET.correo }}">
                {# Campo de texto para ingresar el correo electrónico del proveedor #}
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="telefono">Teléfono</label>
                <input type="text" class="form-control" id="telefono" name="telefono" placeholder="Ingrese el teléfono" value="{{ request.GET.telefono }}">
                {# Campo de texto para ingresar el teléfono del proveedor #}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="ciudad">Ciudad</label>
                <input type="text" class="form-control" id="ciudad" name="ciudad" placeholder="Ingrese la ciudad" value="{{ request.GET.ciudad }}">
                {# Campo de texto para ingresar la ciudad del proveedor #}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="direccion">Dirección</label>
                <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ingrese la dirección" value="{{ request.GET.direccion }}">
                {# Campo de texto para ingresar la dirección del proveedor #}
            </div>
        </div>
    </div>
    
</form>
{% endblock %}

{% block columnas %}
{# Bloque para definir las columnas de la tabla #}
<tr>
    <th scope="col">Id</th>
    <th scope="col">Tipo de Persona</th>
    <th scope="col">Nombres / Razón Social</th>
    <th scope="col">Tipo de Documento</th>
    <th scope="col">Número de Documento</th>
    <th scope="col">Correo</th>
    <th scope="col">Teléfono</th>
    <th scope="col">Ciudad</th>
    <th scope="col">Dirección</th>
    <th scope="col">Opciones</th>
</tr>
{% endblock %}

{% block filas %}
{# Bloque para definir las filas de la tabla #}
{% for p in object_list %}
<tr>
    <td>{{ p.id }}</td>
    <td>{{ p.get_tipo_persona_display }}</td>
    <td>{{ p.nombres }}</td>
    <td>{{ p.get_tipo_documento_display }}</td>
    <td>{{ p.numero_documento }}</td>
    <td>{{ p.correo }}</td>
    <td>{{ p.telefono }}</td>
    <td>{{ p.ciudad }}</td>
    <td>{{ p.direccion }}</td>
    <td>
        <a href="{% url 'app:proveedor_editar' p.id %}" class="btn btn-info btn-sm" title="Editar proveedor">
            <i class="fas fa-edit"></i>
        </a>
        {% if request.user.is_superuser or request.user.is_staff %}
            <a href="#" class="btn btn-danger btn-sm delete-button" data-id="{{ p.id }}" title="Eliminar proveedor">
                <i class="fas fa-trash"></i>
            </a>
        {% else %}
            <span class="btn btn-danger btn-sm disabled" title="Eliminar proveedor">
                <i class="fas fa-trash"></i>
            </span>
        {% endif %}

        <!-- Scripts de accesibilidad y AdminLTE -->
        <script src="{% static 'node_modules/sienna-accessibility/sienna.js' %}?v1.1"></script>
        <script src="{% static 'node_modules/sienna-accessibility/custom.js' %}?v1.1"></script>
        <script src="{% static 'lib/adminlte-3.2.0/js/demo.js'%}?v1.1"></script>
        <script src="{% static 'lib/adminlte-3.2.0/js/adminlte.js' %}?v1.1"></script>
        <script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>
        <script>
            document.querySelectorAll('.delete-button').forEach(function(button) {
                button.addEventListener('click', function(e) {
                    e.preventDefault();
                    let proveedorId = this.getAttribute('data-id');
                    let deleteUrl = "{% url 'app:proveedor_eliminar' 0 %}".replace('0', proveedorId);
                    
                    Swal.fire({
                        title: 'Confirmación',
                        text: '¿Estás seguro de que deseas eliminar este proveedor?',
                        icon: 'question',
                        showCancelButton: true,
                        confirmButtonText: 'Sí, Eliminar',
                        cancelButtonText: 'Cancelar',
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            // Enviar solicitud AJAX para eliminar la categoría
                            fetch(deleteUrl, {
                                method: 'POST',
                                headers: {
                                    'X-CSRFToken': '{{ csrf_token }}',  // Asegúrate de enviar el token CSRF
                                    'Content-Type': 'application/json',
                                },
                            })
                            .then(response => response.json())
                            .then(data => {
                                if (data.status === 'success') {
                                    Swal.fire({
                                        title: 'Eliminación Exitosa',
                                        text: 'El proveedor ha sido eliminado correctamente.',
                                        icon: 'success',
                                        confirmButtonText: 'Continuar',
                                        backdrop: true,
                                        timer: 1500,
                                        timerProgressBar: true,
                                        position: 'center',
                                        allowOutsideClick: false,
                                        allowEscapeKey: false,
                                        allowEnterKey: false,
                                        stopKeydownPropagation: false,
                                        buttonsStyling: true,
                                        showCloseButton: true,
                                        closeButtonAriaLabel: 'Cerrar alerta',
                                    }).then(() => {
                                        // Recargar la página después de eliminar
                                        location.reload();
                                    });
                                } else {
                                    Swal.fire({
                                        title: 'Error',
                                        text: data.message,
                                        icon: 'error',
                                    });
                                }
                            })
                            .catch(error => {
                                Swal.fire({
                                    title: 'Error',
                                    text: 'Ocurrió un error al eliminar el proveedor.',
                                    icon: 'error',
                                });
                            });
                        }
                    });
                });
            });
        </script> 
    </td>
</tr>
{% endfor %}
{% endblock %}