Config/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import*
from inicio.views import IndexView
from login.views import *
from dashboard.views import*
from django.contrib.auth import views as auth_views
from inicio.views import enviar_correo

urlpatterns = [
    path('', IndexView.as_view(), name='index_pr'),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('app/',include ('app.urls')),
    # path('password_reset/',auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html'), name='password_reset'), 
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'), name='password_reset_done'), 
    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'),name='password_reset_confirm'), 
    # path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'), name='password_reset_complete'),  
    path('enviar_correo/', enviar_correo, name='enviar_correo'),                                                                                                                     
]

app/urls.py
from django.urls import path
from app.views.backup.views import *
from app.views.Categoria.views import *
from app.views.Ubicacion.views import *
from app.views.Proveedor.views import * 
from app.views.Cliente.views import *
from app.views.Tipo.views import *
from app.views.Producto.views import *
from app.views.Normativa.views import *
from app.views.Ventas.views import *
from app.views.Compras.views import *
from app.views.Stock.views import *
from app.views.Usuario.views import *
from app.views.Dcompras.views import *
from app.views.Dventas.views import *
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'app'

urlpatterns = [

    #-------------------------------------------------- Categoría --------------------------------------------------
    
    path('categoria/listar/', CategoriaListView.as_view(), name='categoria_listar'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editarC'),
    path('categoria/eliminar/<int:id_categ>/', CategoriaListView.eliminar_categoria, name='categoria_eliminar'), 
    
    #-------------------------------------------------- Cliente ----------------------------------------------------
    
    path('cliente/listar/', ClienteListView.as_view(), name='cliente_listar'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editarCli'),
    path('cliente/eliminar/<int:id_cliente>/', ClienteListView.EliminarCliente, name='cliente_eliminar'),
    
    #-------------------------------------------------- Compras ----------------------------------------------------
    
    path('compras/listar/', ComprasListView.as_view(), name='compras_listar'),
    path('compras/crear/', ComprasCreateView.as_view(), name='compras_crear'),
    path('compras/editar/<int:pk>/', ComprasUpdateView.as_view(), name='compras_editar'),
    path('obtener-datos-proveedor/', obtener_datos_proveedor, name='obtener_datos_proveedor'),
    path('compras/<int:compra_id>/cambiar-estado/', cambiar_estado_compra, name='cambiar_estado_compra'),
    
    
        #-------------------------------------------------- Dcompras --------------------------------------------------------
    
    path('detalle-compras/listar/', DetalleCompraListView.as_view(), name='detallecompra_listar'),
    path('detalle-compras/crear/', DetalleCompraCreateView.as_view(), name='detallecompra_crear'),
    path('detalle-compras/editar/<int:pk>/', DetalleCompraUpdateView.as_view(), name='detallecompra_editar'),
    path('detalle-compras/eliminar/<int:id_compraD>/', DetalleCompraListView.EliminarComprasD,name='detallecompra_eliminar'),
    path('compras/detalles/<int:compra_id>/', DetalleCompraCreateView.as_view(), name='detalle_compra'),
    
    
    #-------------------------------------------------- Normativa --------------------------------------------------
    
    path('normativa/listar/', NormativaListView.as_view(), name='normativa_listar'),
    path('normativa/crear/', NormativaCreateView.as_view(), name='normativa_crear'),
    path('normativa/editar/<int:pk>/', NormativaUpdateView.as_view(), name='normativa_editarN'),
    path('normativa/eliminar/<int:id_norma>/', NormativaListView.EliminarNormativa, name='normativa_eliminar'),
    
    #-------------------------------------------------- Usuario ---------------------------------------------------
    
    path('usuario/listar/', UsuarioListView.as_view(), name='usuario_listar'),
    path('usuario/crear/', UsuarioCreateView.as_view(), name='usuario_crear'),
    path('usuario/editar/<int:pk>/', UsuarioUpdateView.as_view(), name='usuario_editar'),
    path('usuario/eliminar/<int:id_usuario>/', UsuarioListView.EliminarUsuario, name='usuario_eliminar'),
    path('acceso_denegado/', TemplateView.as_view(template_name='acceso_denegado.html'), name='acceso_denegado'),
    
    #-------------------------------------------------- Producto --------------------------------------------------

    path('producto/listar/', ProductoListView.as_view(), name='producto_listar'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editarP'),
    path('producto/eliminar/<int:id_producto>/', ProductoListView.EliminarProducto, name='producto_eliminar'),
    
    #-------------------------------------------------- Proveedor --------------------------------------------------
    
    path('proveedor/listar/', ProveedorListView.as_view(), name='proveedor_listar'),
    path('proveedor/crear/', ProveedorCreateView.as_view(), name='proveedor_crear'),
    path('proveedor/editar/<int:pk>/', ProveedorUpdateView.as_view(), name='proveedor_editar'),
    path('proveedor/eliminar/<int:id_prove>/', ProveedorListView.EliminarProveedor, name='proveedor_eliminar'),
    
    #-------------------------------------------------- Tipos de productos -----------------------------------------

    path('tipo/listar/', TipoListView.as_view(), name='tipo_listar'),
    path('tipo/crear/', TipoCreateView.as_view(), name='tipo_crear'),
    path('tipo/editar/<int:pk>/', TipoUpdateView.as_view(), name='tipo_editarTP'),
    path('tipo/eliminar/<int:id_tipo>/', TipoListView.EliminarTipo, name='tipo_eliminar'),

    #-------------------------------------------------- Ubicación --------------------------------------------------
    
    path('ubicacion/listar/', UbicacionListView.as_view(), name='ubicacion_listar'),
    path('ubicacion/crear/', UbicacionCreateView.as_view(), name='ubicacion_crear'),
    path('ubicacion/eliminar/<int:id_ubica>/', UbicacionListView.EliminarUbicacion, name='ubicacion_eliminar'),
    path('municipios-por-departamento/', municipios_por_departamento, name='municipios_por_departamento'),

    #-------------------------------------------------- Ventas ----------------------------------------------------
    path('ventas/listar/', VentasListView.as_view(), name='venta_listar'),
    path('ventas/crear/', VentasCreateView.as_view(), name='venta_crear'),
    path('ventas/editar/<int:pk>/', VentasUpdateView.as_view(), name='venta_editar'),
    path('cambiar-estado-venta/<int:venta_id>/',cambiar_estado_venta, name='cambiar_estado_venta'),

    #-------------------------------------------------- Dventas ---------------------------------------------------
    
    path('detalle-venta/', DetalleVentaListView.as_view(), name='detalleventa_listar'),
    path('detalle-venta/editar/<int:pk>/', DetalleVentaUpdateView.as_view(), name='detalleventa_editar'),
    path('ventas/detalle/<int:venta_id>/', VentaDetalleCreateView.as_view(), name='detalle_venta'),

    #-------------------------------------------------- Backup del sistema ----------------------------------------
    
    path('backup/', backup_view, name='backup'),
    path('backup/create/', backup_database, name='respaldo'),
    path('backup/restore/', restore_database, name='restauracion'),
    path('backup/delete/', delete_backup, name='eliminar_archivo'),

    #-------------------------------------------------- Stock -----------------------------------------------------
    
    path('stock/listar/', StockListView.as_view(), name='listar_stock'),
]

if settings.DEBUG:
    urlpatterns += static('/backups/', document_root=settings.BACKUP_ROOT)

app/views/Compras/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.http import JsonResponse
from app.models import Compras, Proveedor ,DetalleCompra
from app.forms import ComprasForm,ComprasEditForm
from django.shortcuts import get_object_or_404,render
from django.utils.dateparse import parse_date
from app.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

class ComprasListView(LoginRequiredMixin,ListView):
    model = Compras
    template_name = 'Compras/listar.html'
    context_object_name = 'compras'

    def post(self, request, *args, **kwargs):
        data = {'Nombre': 'Admin'}
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Listado de Compras'
        context['entidad'] = 'Compras'
        context['crear_url'] = reverse_lazy('app:compras_crear')
        context['proveedores'] = Proveedor.objects.all()  # Añade la lista de proveedores al contexto
        # Agregar breadcrumbs
        context['breadcrumbs'] = [
            {'nombre': 'Modulo', 'url': '/dashboard'},
            {'nombre': 'Compras', 'url': reverse_lazy('app:compras_listar')},
        ]
        return context

    def get_queryset(self):
        queryset = super().get_queryset()

        # Filtrar por número de factura
        num_factura = self.request.GET.get('num_factura', None)
        if num_factura:
            queryset = queryset.filter(num_factura__icontains=num_factura)

        # Filtrar por fecha de compra
        fecha_compra = self.request.GET.get('fecha_compra', None)
        if fecha_compra:
            # Usar parse_date para evitar problemas con la hora
            fecha_compra = parse_date(fecha_compra)
            if fecha_compra:
                queryset = queryset.filter(fecha_compra=fecha_compra)

        # Filtrar por proveedor
        proveedor_id = self.request.GET.get('proveedor', None)
        if proveedor_id:
            queryset = queryset.filter(proveedor__id=proveedor_id)  # Filtra por ID de proveedor

        return queryset
    
class ComprasCreateView(LoginRequiredMixin,CreateView):
    model = Compras
    form_class = ComprasForm
    template_name = 'Compras/crear.html'
    success_url = reverse_lazy('app:compras_listar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['proveedores'] = Proveedor.objects.all()
        context['titulo'] = 'Crear Compra'
        context['entidad'] = 'Compras'
        context['listar_url'] = reverse_lazy('app:compras_listar')
        # Agregar breadcrumbs
        context['breadcrumbs'] = [
            {'nombre': 'Modulo', 'url': '/dashboard'},
            {'nombre': 'Compras', 'url': reverse_lazy('app:compras_listar')},
            {'nombre': 'Crear Compra', 'url': reverse_lazy('app:compras_crear')},
        ]
        
        return context
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({
            'success': True,
            'message': 'Venta creada exitosamente',
        })

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return super().form_invalid(form)

class ComprasUpdateView(LoginRequiredMixin, UpdateView):
    model = Compras
    form_class = ComprasEditForm
    template_name = 'Compras/editarCom.html'
    success_url = reverse_lazy('app:compras_listar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Actualizar Compra'
        context['entidad'] = 'Compras'
        context['listar_url'] = reverse_lazy('app:compras_listar')
        # Añadir breadcrumbs
        context['breadcrumbs'] = [
            {'nombre': 'Modulo', 'url': '/dashboard'},
            {'nombre': 'Compras', 'url': reverse_lazy('app:compras_listar')},
            {'nombre': 'Editar Compra', 'url': reverse_lazy('app:compras_editar', args=[self.object.pk])},
        ]
        
        return context
    def form_valid(self, form):
        # Guardar el formulario como está, ya que la validación se realiza en el formulario
        form.save()  # Guarda el objeto

        return JsonResponse({
            'success': True,
            'message': 'Factura actualizada correctamente',
        })

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return super().form_invalid(form)

def obtener_datos_proveedor(request):
    proveedor_id = request.GET.get('proveedor_id')
    try:
        proveedor = Proveedor.objects.get(id=proveedor_id)
        data = {
            'nombre': proveedor.nombres if proveedor.tipo_persona == 'PN' else proveedor.razon_social,
            'direccion': proveedor.direccion,
            'correo': proveedor.correo,
            'telefono': proveedor.telefono,
        }
        return JsonResponse(data)
    except Proveedor.DoesNotExist:
        return JsonResponse({'error': 'Proveedor no encontrado.'}, status=404)

@login_required
def compra_detalle(request, num_factura):
    compra = get_object_or_404(Compras, num_factura=num_factura)
    detalles_compra = DetalleCompra.objects.filter(compra=compra)
    form = ComprasForm(instance=compra)
    
    context = {
        'form': form,
        'titulo': 'Detalles de Compra',
        'listar_url': reverse_lazy('app:compras_listar'),
        'detalles_compra': detalles_compra,  # Pasamos los detalles de la compra al contexto
    }
    return render(request, 'Compras/CompraD.html', context)

def cambiar_estado_compra(request, compra_id):
    # Obtener la compra
    compra = get_object_or_404(Compras, id=compra_id)
    
    # Cambiar el estado de "editable" a "bloqueado" y viceversa
    if compra.estado == 'editable':
        compra.estado = 'bloqueado'
    else:
        compra.estado = 'editable'
    
    # Guardar el cambio en la base de datos
    compra.save()
    
    # Redirigir a la lista de compras
    return redirect('app:compras_listar')  

app/templates/Compras/crear.html
{% extends 'listar.html' %}

{% load static %}
{% load widget_tweaks %}

{% block contenido %}

<form method="post" action="." id="createForm">
    <div class="card card-default">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                {% for breadcrumb in breadcrumbs %}
                    <li class="breadcrumb-item">
                        <a href="{{ breadcrumb.url }}">{{ breadcrumb.nombre }}</a>
                    </li>
                {% endfor %}
            </ol>
        </nav>
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-plus"></i>
                {{ titulo }}
            </h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <div id="alert-container"></div>
            {% if form.errors %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                <h5><i class="icon fas fa-ban"></i>
                    {% if form.instance.pk %}
                        Ha ocurrido un error al intentar {{ titulo }}.
                    {% else %}
                        Ha ocurrido un error al intentar crear {{ titulo }}.
                    {% endif %}
                </h5>
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                <div class="invalid-feedback">
                    {{ field.errors|striptags }}
                </div>
                <div class="mandatory-feedback" style="display:none; color: red;">Este campo es obligatorio</div>
            </div>
            {% endfor %}
        </div>
        <div class="card-footer">
            <button type="button" class="btn btn-success" id="confirmButton">
                <i class="fas fa-save"></i> Confirmar
            </button>
            <a href="{{ listar_url }}" class="btn btn-danger custom-btn print-hidden">
                <i class="fas fa-times"></i> Cancelar
            </a>
        </div>
    </div>
</form>

<script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>

<script>
    document.getElementById('confirmButton').addEventListener('click', function(e) {
        e.preventDefault(); 

        // Validación de campos vacíos y fecha de compra
        let isValid = true;
        let formFields = document.querySelectorAll('#createForm .form-control');
        let fechaCompraField = document.querySelector('[name="fecha_compra"]');
        let today = new Date().toISOString().split('T')[0];  // Fecha actual en formato YYYY-MM-DD

        formFields.forEach(function(field) {
            let feedback = field.parentNode.querySelector('.mandatory-feedback');
            if (field.value.trim() === '') {
                isValid = false;
                field.classList.add('is-invalid');
                feedback.style.display = 'block'; // Mostrar mensaje de campo obligatorio
            } else {
                field.classList.remove('is-invalid');
                feedback.style.display = 'none'; // Ocultar mensaje si el campo es válido
            }
        });

        // Validar si la fecha de compra es mayor o menor a la fecha actual
        if (fechaCompraField.value && (fechaCompraField.value < today || fechaCompraField.value > today)) {
            isValid = false;
            Swal.fire({
                title: 'Fecha Inválida',
                text: 'La fecha de creación de la compra debe ser la actual. No se permiten fechas anteriores ni posteriores.',
                icon: 'warning',
                confirmButtonText: 'Aceptar',
                backdrop: true,
                timer: 4000,
                timerProgressBar: true,
                position: 'center',
                allowOutsideClick: true,
            });
            fechaCompraField.classList.add('is-invalid');
            let errorDiv = fechaCompraField.parentNode.querySelector('.invalid-feedback');
            errorDiv.innerHTML = 'La fecha de creación de la compra debe ser la actual. No se permiten fechas anteriores ni posteriores.';
            return;  // Detener la ejecución si la fecha es inválida
        } else {
            fechaCompraField.classList.remove('is-invalid');
        }

        if (!isValid) {
            Swal.fire({
                title: 'Campo vacío',
                text: 'Debe llenar todos los campos de registro.',
                icon: 'warning',
                confirmButtonText: 'Aceptar',
                backdrop: true,
                timer: 3000,
                timerProgressBar: true,
                position: 'center',
                allowOutsideClick: true,
            });
            return; // Detener la ejecución si hay campos vacíos
        }

        // Obtener los datos del formulario
        let formData = new FormData(document.getElementById('createForm'));

        // Enviar los datos mediante AJAX
        fetch(".", {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        })
        .then(response => {
            if (!response.ok) {
                return response.json().then(data => { throw data; });
            }
            return response.json();
        })
        .then(data => {
            if (data.success) {
                Swal.fire({
                    title: 'Registrado Correctamente',
                    text: 'La compra ha sido registrada exitosamente.',
                    icon: 'success',
                    confirmButtonText: 'Continuar',
                    backdrop: true,
                    timer: 2000,
                    timerProgressBar: true,
                    position: 'center',
                    allowOutsideClick: false,
                }).then(() => {
                    window.location.href = "{{ listar_url }}"; // Redirigir al listado
                });
            }
        })
        .catch(data => {
            // Mostrar alerta de error
            const errorMessage = data.message;
            const specificErrors = data.errors; // Obtenemos errores específicos
        
            // Si hay errores específicos, los recopilamos en un solo mensaje
            let detailedMessages = [];
        
            if (specificErrors) {
                if (specificErrors.num_factura) {
                    detailedMessages.push(specificErrors.num_factura[0]); // Agregar mensaje de num_factura
                }
                if (specificErrors.fecha_emision) {
                    detailedMessages.push(specificErrors.fecha_emision[0]); // Agregar mensaje de fecha_emision
                }
                if (specificErrors.cliente) {
                    detailedMessages.push(specificErrors.cliente[0]); // Agregar mensaje de cliente
                }
            }
        
            // Unimos los mensajes detallados con saltos de línea HTML
            let detailedMessage = detailedMessages.length > 0 ? detailedMessages.join('<br>') : '';
        
            Swal.fire({
                title: 'Inválido',
                html: detailedMessage || errorMessage,
                icon: 'warning',
                confirmButtonText: 'Aceptar',
            });
        
            // Resaltar los campos con errores y mostrar debajo del campo
            if (specificErrors) {
                Object.keys(specificErrors).forEach(function(key) {
                    let field = document.querySelector(`[name=${key}]`);
                    if (field) {
                        field.classList.add('is-invalid');
                        let errorDiv = field.parentNode.querySelector('.invalid-feedback');
                        if (errorDiv) {
                            errorDiv.innerHTML = specificErrors[key][0];  // Mostrar el error debajo del campo
                        }
                    }
                });
            }
        });
    });
</script>

{% endblock %}

app/templates/Compras/listar.html
{% extends 'listar.html' %}

{% load static %}

{% block filtro_form_contenido %}
<form method="GET" action="{% url 'app:compras_listar' %}">
    <div class="row">
        <!-- Filtro por Número de Factura -->
        <div class="col-md-4">
            <div class="form-group">
                <label for="num_factura">Número de Factura</label>
                <input type="text" class="form-control" id="num_factura" name="num_factura"
                    placeholder="Ingrese el número de factura" value="{{ request.GET.num_factura }}">
            </div>
        </div>

        <!-- Filtro por Fecha de Compra -->
        <div class="col-md-4">
            <div class="form-group">
                <label for="fecha_compra">Fecha de Compra</label>
                <input type="date" class="form-control" id="fecha_compra" name="fecha_compra"
                    value="{{ request.GET.fecha_compra }}">
            </div>
        </div>

        <!-- Filtro por Proveedor -->
        <div class="col-md-4">
            <div class="form-group">
                <label for="proveedor">Proveedor</label>
                <select class="form-control" id="proveedor" name="proveedor">
                    <option value="">Seleccione un proveedor</option>
                    {% for proveedor in proveedores %}
                        <option value="{{ proveedor.id }}" 
                            {% if proveedor.id|stringformat:"s" == request.GET.proveedor %}selected{% endif %}>
                            {{ proveedor.nombres }}
                        </option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
</form>
{% endblock %}

{% block columnas %}
{# Bloque para los encabezados de la tabla #}
<tr>
    <th scope="col">ID</th>
    <th scope="col">Número de Factura</th>
    <th scope="col">Fecha de Compra</th>
    <th scope="col">Proveedor</th>
    <th scope="col">Opciones</th>
</tr>
{% endblock %}

{% block filas %}
{# Bloque para las filas de la tabla #}
{% for com in object_list %}
<tr>
    <td>{{ com.id }}</td>
    <td>{{ com.num_factura }}</td>
    <td>{{ com.fecha_compra }}</td>
    <td>{{ com.proveedor }}</td>
    <td>
        <!-- Botón para editar la compra -->
        <a href="{% url 'app:compras_editar' com.id %}" class="btn btn-info btn-sm" title="Editar compra">
            <i class="fas fa-edit"></i>
        </a>

        <!-- Botón para ver los detalles de la compra -->
        <a href="{% url 'app:detalle_compra' compra_id=com.id %}" class="btn btn-sm" style="background-color: #23853a; color: white;" title="Detalle Compra">
            <i class="fas fa-plus"></i>
        </a>

        <!-- Botón para cambiar el estado de la compra -->
        {% if com.estado == 'editable' %}
            <a href="{% url 'app:cambiar_estado_compra' com.id %}" class="btn btn-warning btn-sm" title="Bloquear compra">
                <i class="fas fa-lock"></i> Bloquear
            </a>
        {% else %}
            <a href="{% url 'app:cambiar_estado_compra' com.id %}" class="btn btn-success btn-sm" title="Desbloquear compra">
                <i class="fas fa-unlock"></i> Desbloquear
            </a>
        {% endif %}
    </td>
</tr>
{% endfor %}
{% endblock %}