Config/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import*
from inicio.views import IndexView
from login.views import *
from dashboard.views import*
from django.contrib.auth import views as auth_views
from inicio.views import enviar_correo

urlpatterns = [
    path('', IndexView.as_view(), name='index_pr'),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('app/',include ('app.urls')),
    # path('password_reset/',auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html'), name='password_reset'), 
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'), name='password_reset_done'), 
    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'),name='password_reset_confirm'), 
    # path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'), name='password_reset_complete'),  
    path('enviar_correo/', enviar_correo, name='enviar_correo'),                                                                                                                     
]

app/urls.py
from django.urls import path
from app.views.backup.views import *
from app.views.Categoria.views import *
from app.views.Ubicacion.views import *
from app.views.Proveedor.views import * 
from app.views.Cliente.views import *
from app.views.Tipo.views import *
from app.views.Producto.views import *
from app.views.Normativa.views import *
from app.views.Ventas.views import *
from app.views.Compras.views import *
from app.views.Stock.views import *
from app.views.Usuario.views import *
from app.views.Dcompras.views import *
from app.views.Dventas.views import *
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'app'

urlpatterns = [

    #-------------------------------------------------- Categoría --------------------------------------------------
    
    path('categoria/listar/', CategoriaListView.as_view(), name='categoria_listar'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editarC'),
    path('categoria/eliminar/<int:id_categ>/', CategoriaListView.eliminar_categoria, name='categoria_eliminar'), 
    
    #-------------------------------------------------- Cliente ----------------------------------------------------
    
    path('cliente/listar/', ClienteListView.as_view(), name='cliente_listar'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editarCli'),
    path('cliente/eliminar/<int:id_cliente>/', ClienteListView.EliminarCliente, name='cliente_eliminar'),
    
    #-------------------------------------------------- Compras ----------------------------------------------------
    
    path('compras/listar/', ComprasListView.as_view(), name='compras_listar'),
    path('compras/crear/', ComprasCreateView.as_view(), name='compras_crear'),
    path('compras/editar/<int:pk>/', ComprasUpdateView.as_view(), name='compras_editar'),
    path('obtener-datos-proveedor/', obtener_datos_proveedor, name='obtener_datos_proveedor'),
    path('compras/<int:compra_id>/cambiar-estado/', cambiar_estado_compra, name='cambiar_estado_compra'),
    
    
        #-------------------------------------------------- Dcompras --------------------------------------------------------
    
    path('detalle-compras/listar/', DetalleCompraListView.as_view(), name='detallecompra_listar'),
    path('detalle-compras/crear/', DetalleCompraCreateView.as_view(), name='detallecompra_crear'),
    path('detalle-compras/editar/<int:pk>/', DetalleCompraUpdateView.as_view(), name='detallecompra_editar'),
    path('detalle-compras/eliminar/<int:id_compraD>/', DetalleCompraListView.EliminarComprasD,name='detallecompra_eliminar'),
    path('compras/detalles/<int:compra_id>/', DetalleCompraCreateView.as_view(), name='detalle_compra'),
    
    
    #-------------------------------------------------- Normativa --------------------------------------------------
    
    path('normativa/listar/', NormativaListView.as_view(), name='normativa_listar'),
    path('normativa/crear/', NormativaCreateView.as_view(), name='normativa_crear'),
    path('normativa/editar/<int:pk>/', NormativaUpdateView.as_view(), name='normativa_editarN'),
    path('normativa/eliminar/<int:id_norma>/', NormativaListView.EliminarNormativa, name='normativa_eliminar'),
    
    #-------------------------------------------------- Usuario ---------------------------------------------------
    
    path('usuario/listar/', UsuarioListView.as_view(), name='usuario_listar'),
    path('usuario/crear/', UsuarioCreateView.as_view(), name='usuario_crear'),
    path('usuario/editar/<int:pk>/', UsuarioUpdateView.as_view(), name='usuario_editar'),
    path('usuario/eliminar/<int:id_usuario>/', UsuarioListView.EliminarUsuario, name='usuario_eliminar'),
    path('acceso_denegado/', TemplateView.as_view(template_name='acceso_denegado.html'), name='acceso_denegado'),
    
    #-------------------------------------------------- Producto --------------------------------------------------

    path('producto/listar/', ProductoListView.as_view(), name='producto_listar'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editarP'),
    path('producto/eliminar/<int:id_producto>/', ProductoListView.EliminarProducto, name='producto_eliminar'),
    
    #-------------------------------------------------- Proveedor --------------------------------------------------
    
    path('proveedor/listar/', ProveedorListView.as_view(), name='proveedor_listar'),
    path('proveedor/crear/', ProveedorCreateView.as_view(), name='proveedor_crear'),
    path('proveedor/editar/<int:pk>/', ProveedorUpdateView.as_view(), name='proveedor_editar'),
    path('proveedor/eliminar/<int:id_prove>/', ProveedorListView.EliminarProveedor, name='proveedor_eliminar'),
    
    #-------------------------------------------------- Tipos de productos -----------------------------------------

    path('tipo/listar/', TipoListView.as_view(), name='tipo_listar'),
    path('tipo/crear/', TipoCreateView.as_view(), name='tipo_crear'),
    path('tipo/editar/<int:pk>/', TipoUpdateView.as_view(), name='tipo_editarTP'),
    path('tipo/eliminar/<int:id_tipo>/', TipoListView.EliminarTipo, name='tipo_eliminar'),

    #-------------------------------------------------- Ubicación --------------------------------------------------
    
    path('ubicacion/listar/', UbicacionListView.as_view(), name='ubicacion_listar'),
    path('ubicacion/crear/', UbicacionCreateView.as_view(), name='ubicacion_crear'),
    path('ubicacion/eliminar/<int:id_ubica>/', UbicacionListView.EliminarUbicacion, name='ubicacion_eliminar'),
    path('municipios-por-departamento/', municipios_por_departamento, name='municipios_por_departamento'),

    #-------------------------------------------------- Ventas ----------------------------------------------------
    path('ventas/listar/', VentasListView.as_view(), name='venta_listar'),
    path('ventas/crear/', VentasCreateView.as_view(), name='venta_crear'),
    path('ventas/editar/<int:pk>/', VentasUpdateView.as_view(), name='venta_editar'),
    path('cambiar-estado-venta/<int:venta_id>/',cambiar_estado_venta, name='cambiar_estado_venta'),

    #-------------------------------------------------- Dventas ---------------------------------------------------
    
    path('detalle-venta/', DetalleVentaListView.as_view(), name='detalleventa_listar'),
    path('detalle-venta/editar/<int:pk>/', DetalleVentaUpdateView.as_view(), name='detalleventa_editar'),
    path('ventas/detalle/<int:venta_id>/', VentaDetalleCreateView.as_view(), name='detalle_venta'),

    #-------------------------------------------------- Backup del sistema ----------------------------------------
    
    path('backup/', backup_view, name='backup'),
    path('backup/create/', backup_database, name='respaldo'),
    path('backup/restore/', restore_database, name='restauracion'),
    path('backup/delete/', delete_backup, name='eliminar_archivo'),

    #-------------------------------------------------- Stock -----------------------------------------------------
    
    path('stock/listar/', StockListView.as_view(), name='listar_stock'),
]

if settings.DEBUG:
    urlpatterns += static('/backups/', document_root=settings.BACKUP_ROOT)

inicio/models.py
from django.db import models

# Create your models here.

app/views/backup/views.py
import os
import datetime
from django.shortcuts import render
from django.http import JsonResponse
from django.conf import settings
import subprocess
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

# Vista para realizar el backup de la base de datos
@login_required
def backup_view(request):
    # Definir la ruta donde se almacenan los archivos de backup
    backup_dir = os.path.join(settings.BASE_DIR, 'backups')

    archivos_backup = []
    if os.path.exists(backup_dir):
        # Obtener todos los archivos con extensión .sql en el directorio de backups
        for archivo in os.listdir(backup_dir):
            if archivo.endswith('.sql'):
                # Ruta completa del archivo
                archivo_path = os.path.join(backup_dir, archivo)
                # Obtener la fecha de creación del archivo
                timestamp = os.path.getctime(archivo_path)
                fecha_creacion = datetime.datetime.fromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S')

                # Agregar a la lista como diccionario con el nombre del archivo y la fecha de creación
                archivos_backup.append({
                    'nombre': archivo,
                    'fecha_creacion': fecha_creacion
                })

        # Ordenarlos por fecha de creación, el más reciente primero
        archivos_backup.sort(key=lambda x: x['fecha_creacion'], reverse=True)

    # Pasar la lista de archivos al contexto de la plantilla
    contexto = {
        'archivos_backup': archivos_backup,
    }

    return render(request, 'backup.html', contexto)



@login_required  # Solo los usuarios autenticados pueden crear un backup
def backup_database(request):
    if request.method == 'POST':
        backup_dir = os.path.join(settings.BASE_DIR, 'backups')
        os.makedirs(backup_dir, exist_ok=True)

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_file = os.path.join(backup_dir, f'backup_{timestamp}.sql')

        try:
            db_name = settings.DATABASES['default']['NAME']
            db_user = settings.DATABASES['default']['USER']
            db_password = settings.DATABASES['default']['PASSWORD']
            db_host = settings.DATABASES['default']['HOST']
            db_port = settings.DATABASES['default']['PORT']

            dump_command = [
                'mysqldump',
                f'--user={db_user}',
                f'--password={db_password}',
                f'--host={db_host}',
                f'--port={db_port}',
                db_name,
                f'--result-file={backup_file}'
            ]

            subprocess.run(dump_command, check=True)

            # Enviar respuesta JSON
            return JsonResponse({'status': 'success', 'message': 'Copia de seguridad creada exitosamente.'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': f"Error al crear la copia de seguridad: {e}"})



@login_required  # Solo los usuarios autenticados pueden restaurar la base de datos
@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def restore_database(request):
    if request.method == 'POST':
        # Obtener el nombre del archivo desde el formulario
        backup_file = request.POST.get('backup_file')

        # Validar que el archivo existe y tiene la extensión correcta
        backup_path = os.path.join(settings.BASE_DIR, 'backups', backup_file)
        if not os.path.exists(backup_path) or not backup_file.endswith('.sql'):
            return JsonResponse({'status': 'error', 'message': 'Archivo no encontrado o formato incorrecto.'})

        try:
            db_name = settings.DATABASES['default']['NAME']
            db_user = settings.DATABASES['default']['USER']
            db_password = settings.DATABASES['default']['PASSWORD']
            db_host = settings.DATABASES['default']['HOST']
            db_port = settings.DATABASES['default']['PORT']

            # Comando para restaurar la base de datos
            restore_command = [
                'mysql',
                f'--user={db_user}',
                f'--password={db_password}',
                f'--host={db_host}',
                f'--port={db_port}',
                db_name,
            ]

            # Abrir el archivo de backup seleccionado
            with open(backup_path, 'rb') as input_file:
                process = subprocess.Popen(restore_command, stdin=input_file, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                stdout, stderr = process.communicate()

            if process.returncode == 0:
                return JsonResponse({'status': 'success', 'message': 'Base de datos restaurada exitosamente.'})
            else:
                return JsonResponse({'status': 'error', 'message': f"Error al restaurar la base de datos: {stderr.decode('utf-8')}"})


        except Exception as e:
            return JsonResponse({'status': 'error', 'message': f"Error al restaurar la base de datos: {e}"})
    else:
        return JsonResponse({'status': 'error', 'message': "Error al restaurar la base de datos."})



login_required  # Solo los usuarios autenticados pueden eliminar archivos
@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def delete_backup(request):
    if request.method == 'POST':
        archivo = request.POST.get('archivo')
        backup_dir = os.path.join(settings.BASE_DIR, 'backups', archivo)

        try:
            if os.path.exists(backup_dir):
                os.remove(backup_dir)
                return JsonResponse({'status': 'success', 'message': 'Archivo eliminado exitosamente.'})
            else:
                return JsonResponse({'status': 'error', 'message': 'El archivo no existe.'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': f'Error al eliminar el archivo: {e}'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Método no permitido.'})

inicio/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.core.mail import send_mail, EmailMessage
from django.http import JsonResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_protect

class IndexView(TemplateView):
    template_name = 'index.html'

@csrf_protect
def enviar_correo(request):
    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            email = request.POST.get('email')
            subject = request.POST.get('subject')
            message = request.POST.get('message')
            image = request.FILES.get('image')

            if not all([name, email, subject, message]):
                raise ValueError("Todos los campos son obligatorios.")

            # Mejorar el mensaje
            full_message = (
                f"Nuevo mensaje recibido:\n\n"
                f"Nombre: {name}\n"
                f"Email: {email}\n"
                f"Asunto: {subject}\n\n"
                f"Mensaje:\n{message}\n\n"
                f"Este mensaje ha sido enviado desde el formulario de contacto de la página de Conaldex."
            )

            # Enviar el correo
            email_message = EmailMessage(
                subject,
                full_message,
                settings.DEFAULT_FROM_EMAIL,
                ["boyacaconaldex@gmail.com"],
            )

            if image:
                email_message.attach(image.name, image.read(), image.content_type)

            email_message.send(fail_silently=False)
            
            return JsonResponse({'message': 'La información se envió correctamente!!!', 'error': 'false'}, status=200)
        
        except ValueError as ve:
            return JsonResponse({'message': str(ve), 'error': 'true'}, status=400)
        except Exception as e:
            return JsonResponse({'message': 'Error al enviar el correo: ' + str(e), 'error': 'true'}, status=500)
    
    return JsonResponse({'message': 'No hemos podido completar la solicitud. {enviar_correo} no encontrado', 'error': 'true'}, status=405)

app/templates/backup.html
{% extends "layout.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/dataTables-bs4/css/dataTables.bootstrap4.min.css' %}" />
<link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/datatables-responsive/css/responsive.bootstrap4.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/respaldo/backup.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
<title>Backup de Base de Datos</title>
<link rel="stylesheet" href="{% static 'lib/sweetalert2/sweetalert2.min.css' %}">
{% endblock %}

{% block contenido %}
<div class="backup-container">
    <div class="backup-header">
        <h1>Copia de Seguridad de la Base de Datos</h1>
    </div>
    
    <!-- Sección para crear una nueva copia de seguridad -->
    <div class="backup-form">
        <div class="form-section backup-section">
            <h2>Crear copia de seguridad</h2>
            <form id="backup-form" method="POST" action="{% url 'app:respaldo' %}">
                {% csrf_token %}
                <button type="submit" class="backup-button" id="create-backup-button">Crear</button>
            </form>
        </div>

        <!-- Sección de restauración -->
        <div class="form-section">
            <h2 style="text-align: center;">Archivos disponibles de copia de seguridad</h2>
            <br>
            <div class="table-responsive">
                <table id="tabla" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Item</th>
                            <th scope="col">Archivos</th>
                            <th scope="col">Fecha de creación</th>
                            <th scope="col">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if archivos_backup %}
                        {% for archivo in archivos_backup %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="/backups/{{ archivo.nombre }}" download>{{ archivo.nombre }}</a></td>
                            <td>{{ archivo.fecha_creacion }}</td>
                            <td>
                                <!-- Formulario para restaurar -->
                                <form id="restore-form" method="POST" action="{% url 'app:restauracion' %}" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="backup_file" value="{{ archivo.nombre }}">
                                    {% if request.user.is_superuser or request.user.is_staff %}
                                    <button type="submit" class="btn btn-primary btn-sm" title="Restaurar">
                                        <i class="fas fa-undo"></i>
                                    </button>
                                    {% else %}
                                    <button type="button" class="btn btn-primary btn-sm disabled" title="No tienes permiso para restaurar">
                                        <i class="fas fa-undo"></i>
                                    </button>
                                {% endif %}
                                </form>

                                <!-- Formulario para eliminar -->
                                <form method="POST" action="{% url 'app:eliminar_archivo' %}" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="archivo" value="{{ archivo.nombre }}">
                                    {% if request.user.is_superuser or request.user.is_staff %}
                                    <button type="submit" class="btn btn-danger btn-sm" title="Eliminar">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                {% else %}
                                    <button type="button" class="btn btn-danger btn-sm disabled" title="No tienes permiso para eliminar">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                {% endif %}
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="4">No hay archivos de copia de seguridad disponibles.</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Variables JS para backup y restauración -->
<script>
    const backupUrl = "{% url 'app:respaldo' %}";
    const restoreUrl = "{% url 'app:restauracion' %}";
</script>
{% endblock %}

{% block javascript %}
<script src="{% static 'lib/adminlte-3.2.0/dataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lib/adminlte-3.2.0/dataTables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/adminlte-3.2.0/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/adminlte-3.2.0/dataTables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>
<script src="{% static 'js/respaldo/backup.js' %}"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const backupform = document.querySelectorAll('form[action="{% url "app:respaldo" %}"]');
        const restoreForms = document.querySelectorAll('form[action="{% url "app:restauracion" %}"]');
        const deleteForms = document.querySelectorAll('form[action="{% url "app:eliminar_archivo" %}"]');

        // Manejo de la creación de backup
        backupform.forEach(form => {
            form.addEventListener('submit', function (event) {
                event.preventDefault();
                const formData = new FormData(this);
                fetch(this.action, {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                }).then(response => response.json())
                    .then(data => {
                        Swal.fire({
                            title: data.status === 'success' ? 'Creación exitosa' : 'Error',
                            text: data.message,
                            icon: data.status === 'success' ? 'success' : 'error'
                        }).then(() => {
                            if (data.status === 'success') {
                                location.reload();
                            }
                        });
                    });
            });
        });

        // Manejo de la restauración con confirmación
        restoreForms.forEach(form => {
            form.addEventListener('submit', function (event) {
                event.preventDefault();
                const formData = new FormData(this);
                fetch(this.action, {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                }).then(response => response.json())
                    .then(data => {
                        Swal.fire({
                            title: data.status === 'success' ? 'Restauración exitosa' : 'Error',
                            text: data.message,
                            icon: data.status === 'success' ? 'success' : 'error'
                        }).then(() => {
                            if (data.status === 'success') {
                                location.reload();  // Recargar la página
                            }
                        });
                    });
            });
        });

        // Manejo de eliminación con SweetAlert2
        deleteForms.forEach(form => {
            form.addEventListener('submit', function (event) {
                event.preventDefault();
                const archivoNombre = form.querySelector('input[name="archivo"]').value;
                Swal.fire({
                    title: '¿Estás seguro?',
                    text: `¿Deseas eliminar el archivo "${archivoNombre}"?`,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Sí, eliminar',
                    cancelButtonText: 'Cancelar'
                }).then((result) => {
                    if (result.isConfirmed) {
                        const formData = new FormData(this);
                        fetch(this.action, {
                            method: 'POST',
                            body: formData,
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        }).then(response => response.json())
                            .then(data => {
                                Swal.fire({
                                    title: data.status === 'success' ? 'Eliminado' : 'Error',
                                    text: data.message,
                                    icon: data.status === 'success' ? 'success' : 'error'
                                }).then(() => {
                                    if (data.status === 'success') {
                                        location.reload();  // Recargar la página
                                    }
                                });
                            });
                    }
                });
            });
        });

        // Inicializar DataTables
        $(document).ready(function () {
            $('#tabla').DataTable({
                "order": [[0, "asc"]],
                "language": {
                    "url": "{% static 'lib/adminlte-3.2.0/datatables/Spanish.json' %}"  // Traducción al español
                }
            });
        });
    });
</script>
{% endblock %}

app/templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="#" class="navbar-brand">
            <!-- <img src="{% static 'img/logo1.png' %}" alt="AdminLTE Logo" class="brand-image" style="opacity: .8">
            <span class="brand-text font-weight-light">PosVentas</span> -->
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="/" class="nav-link"><i class="fas fa-home"></i> Inicio</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                    class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Módulos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'app:categoria_listar' %}" class="dropdown-item">
                            <i class="fas fa-layer-group" style="margin-right: 8px;"></i> Categoría</a></li>
                        <li><a href="{% url 'app:ubicacion_listar' %}" class="dropdown-item">
                            <i class="fas fa-map-marker-alt" style="margin-right: 8px;"></i> Ubicación</a></li>
                        <li><a href="{% url 'app:cliente_listar' %}" class="dropdown-item">
                            <i class="fas fa-user-tie" style="margin-right: 8px;"></i> Clientes</a></li>
                        <li><a href="{% url 'app:proveedor_listar' %}" class="dropdown-item">
                            <i class="fas fa-truck" style="margin-right: 8px;"></i> Proveedor</a></li>
                        <li><a href="{% url 'app:tipo_listar' %}" class="dropdown-item">
                            <i class="fas fa-clipboard-list" style="margin-right: 8px;"></i> Tipo producto</a></li>
                        <li><a href="{% url 'app:producto_listar' %}" class="dropdown-item">
                            <i class="fas fa-hard-hat" style="margin-right: 8px;"></i> Productos</a></li>
                        <li><a href="{% url 'app:compras_listar' %}" class="dropdown-item">
                            <i class="fas fa-credit-card" style="margin-right: 8px;"></i> Compras</a></li>
                        <li><a href="{% url 'app:normativa_listar' %}" class="dropdown-item">
                            <i class="fas fa-balance-scale" style="margin-right: 8px;"></i> Normativas</a></li>
                        <li><a href="{% url 'app:listar_stock' %}" class="dropdown-item">
                            <i class="fas fa-cubes" style="margin-right: 8px;"></i> Stock</a></li>
                        <li><a href="{% url 'app:venta_listar' %}" class="dropdown-item">
                            <i class="fas fa-shopping-cart" style="margin-right: 8px;"></i> Ventas</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <a class="nav-link" href="{% url 'logout' %}" title='cerrar sesión'>
                <i class="fas fa-power-off" aria-hidden="True"></i>
            </a>
        </ul>
    </div>
</nav>

<link rel="stylesheet" href="{% static 'node_modules/sienna-accessibility/custom.css' %}?v1.1" />

{% block javascript %}
<script src="{% static 'node_modules/sienna-accessibility/sienna.js' %}?v1.1"></script>
<script src="{% static 'node_modules/sienna-accessibility/custom.js' %}?V1.1"></script>
<script src="{% static 'lib/adminlte-3.2.0/js/demo.js' %}?V1.1"></script>
<script src="{% static 'lib/adminlte-3.2.0/js/adminlte.js' %}?v1.1"></script>
{% endblock %}

app/templates/layout.html
{% extends 'aside/body.html' %}